//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgeOfBots.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForgeOfBots.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fetch(&quot;https://###WorldServer###.forgeofempires.com/glps/login_check&quot;, {
        ///    &quot;credentials&quot;: &quot;include&quot;,
        ///    &quot;headers&quot;: {
        ///        &quot;User-Agent&quot;: &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0&quot;,
        ///        &quot;Accept&quot;: &quot;application/json, text/plain, */*&quot;,
        ///        &quot;Accept-Language&quot;: &quot;de,en-US;q=0.7,en;q=0.3&quot;,
        ///        &quot;X-XSRF-TOKEN&quot;: &quot;###XSRF-TOKEN###&quot;,
        ///        &quot;Content-type&quot;: &quot;application/x-www-form-urlencoded; charset=UTF-8&quot;,
        ///        &quot;X-Requested-With&quot;: &quot;XMLHttpRequest&quot;,
        ///     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string preloadLogin {
            get {
                return ResourceManager.GetString("preloadLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fetch(&quot;https://###WorldServer###0.forgeofempires.com/start/index?action=fetch_worlds_for_login_page&quot;, {
        ///    &quot;credentials&quot;: &quot;include&quot;,
        ///    &quot;headers&quot;: {
        ///        &quot;accept&quot;: &quot;text/plain, */*; q=0.01&quot;,
        ///        &quot;accept-language&quot;: &quot;de&quot;,
        ///        &quot;cache-control&quot;: &quot;no-cache&quot;,
        ///        &quot;content-type&quot;: &quot;application/x-www-form-urlencoded; charset=UTF-8&quot;,
        ///        &quot;pragma&quot;: &quot;no-cache&quot;,
        ///        &quot;sec-fetch-mode&quot;: &quot;cors&quot;,
        ///        &quot;sec-fetch-site&quot;: &quot;same-origin&quot;,
        ///        &quot;x-requested-with&quot;: &quot;XMLHttpRequest&quot;
        ///    },
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string preloadLoginWorld {
            get {
                return ResourceManager.GetString("preloadLoginWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fetch(&quot;https://###WorldServer###0.forgeofempires.com/start/index?action=play_now_login&quot;, {
        ///    &quot;credentials&quot;: &quot;include&quot;,
        ///    &quot;headers&quot;: {
        ///        &quot;User-Agent&quot;: &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0&quot;,
        ///        &quot;Accept&quot;: &quot;text/plain, */*; q=0.01&quot;,
        ///        &quot;Accept-Language&quot;: &quot;de,en-US;q=0.7,en;q=0.3&quot;,
        ///        &quot;Content-Type&quot;: &quot;application/x-www-form-urlencoded; charset=UTF-8&quot;,
        ///        &quot;X-Requested-With&quot;: &quot;XMLHttpRequest&quot;,
        ///        &quot;Pragma&quot;: &quot;no-cache&quot;,
        ///        &quot;C [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string preloadSelectWorld {
            get {
                return ResourceManager.GetString("preloadSelectWorld", resourceCulture);
            }
        }
    }
}
