//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgeOfBots {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForgeOfBots.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attach ähnelt.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attach to Main ähnelt.
        /// </summary>
        public static string AttachMain {
            get {
                return ResourceManager.GetString("AttachMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t sit down ähnelt.
        /// </summary>
        public static string CanNotSitDown {
            get {
                return ResourceManager.GetString("CanNotSitDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clanmembers ähnelt.
        /// </summary>
        public static string Clanmembers {
            get {
                return ResourceManager.GetString("Clanmembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR WHILE COLLECTING PRODUCTION ähnelt.
        /// </summary>
        public static string CollectingError {
            get {
                return ResourceManager.GetString("CollectingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went wrong collecting tavern ähnelt.
        /// </summary>
        public static string CollectingTavernError {
            get {
                return ResourceManager.GetString("CollectingTavernError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collect Tavern ähnelt.
        /// </summary>
        public static string CollectTavern {
            get {
                return ResourceManager.GetString("CollectTavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CRITICAL ERROR:  ähnelt.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently Sitting Players:  ähnelt.
        /// </summary>
        public static string CurrentlySittingPlayers {
            get {
                return ResourceManager.GetString("CurrentlySittingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detach ähnelt.
        /// </summary>
        public static string Detach {
            get {
                return ResourceManager.GetString("Detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detach from Main ähnelt.
        /// </summary>
        public static string DetachMain {
            get {
                return ResourceManager.GetString("DetachMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading  ähnelt.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPIRED ähnelt.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FAILED TO ACTIVATE ähnelt.
        /// </summary>
        public static string FailedToActivate {
            get {
                return ResourceManager.GetString("FailedToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friends ähnelt.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive Friends ähnelt.
        /// </summary>
        public static string InactiveFriends {
            get {
                return ResourceManager.GetString("InactiveFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incident Bot ähnelt.
        /// </summary>
        public static string IncidentBot {
            get {
                return ResourceManager.GetString("IncidentBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incident collected ähnelt.
        /// </summary>
        public static string IncidentCollected {
            get {
                return ResourceManager.GetString("IncidentCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem using this Serial-Key with your Device!!
        ///
        ///Either you activated the Serial-Key on a other Device
        ///or the Serial-Key is not valid! ähnelt.
        /// </summary>
        public static string LicenceNotValid {
            get {
                return ResourceManager.GetString("LicenceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging in... ähnelt.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motivating ähnelt.
        /// </summary>
        public static string Motivating {
            get {
                return ResourceManager.GetString("Motivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motivation DONE ähnelt.
        /// </summary>
        public static string MotivationDone {
            get {
                return ResourceManager.GetString("MotivationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neighbors ähnelt.
        /// </summary>
        public static string Neighbors {
            get {
                return ResourceManager.GetString("Neighbors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Login now... ähnelt.
        /// </summary>
        public static string PleaseLoginNow {
            get {
                return ResourceManager.GetString("PleaseLoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait (again)! ähnelt.
        /// </summary>
        public static string PleaseWaitAgain {
            get {
                return ResourceManager.GetString("PleaseWaitAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait... ähnelt.
        /// </summary>
        public static string PleaseWaitShutdown {
            get {
                return ResourceManager.GetString("PleaseWaitShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutingdown Bot ähnelt.
        /// </summary>
        public static string PleaseWaitShutdown2 {
            get {
                return ResourceManager.GetString("PleaseWaitShutdown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polivate Bot ähnelt.
        /// </summary>
        public static string PolivateBot {
            get {
                return ResourceManager.GetString("PolivateBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PREMIUM ähnelt.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Producing ähnelt.
        /// </summary>
        public static string ProducingState {
            get {
                return ResourceManager.GetString("ProducingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Production Bot ähnelt.
        /// </summary>
        public static string ProductionBot {
            get {
                return ResourceManager.GetString("ProductionBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Production finished! ähnelt.
        /// </summary>
        public static string ProductionFinishedState {
            get {
                return ResourceManager.GetString("ProductionFinishedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing ähnelt.
        /// </summary>
        public static string ProductionIdle {
            get {
                return ResourceManager.GetString("ProductionIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die READY TO COLLECT ähnelt.
        /// </summary>
        public static string ReadyToCollect {
            get {
                return ResourceManager.GetString("ReadyToCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Response from server was not valid ähnelt.
        /// </summary>
        public static string ResponseNotValid {
            get {
                return ResourceManager.GetString("ResponseNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reward ähnelt.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recurring-Quest Bot ähnelt.
        /// </summary>
        public static string RQBot {
            get {
                return ResourceManager.GetString("RQBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Showing Notification ähnelt.
        /// </summary>
        public static string ShowingNotify {
            get {
                return ResourceManager.GetString("ShowingNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sit down ähnelt.
        /// </summary>
        public static string SitDown {
            get {
                return ResourceManager.GetString("SitDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sitting at Tavern ähnelt.
        /// </summary>
        public static string SittingAtTavern {
            get {
                return ResourceManager.GetString("SittingAtTavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR WHILE STARTING NEW PRODUCTION ähnelt.
        /// </summary>
        public static string StartingError {
            get {
                return ResourceManager.GetString("StartingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SUBSCRIPTION EXPIRED ähnelt.
        /// </summary>
        public static string SubExpiredTitle {
            get {
                return ResourceManager.GetString("SubExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Subscription is expired.
        ///
        ///Please purchase a new Subscribtion and acitvate it
        ///Press &apos;Yes&apos; to open the Store
        ///
        ///else you are continue using the Free-Version
        ///Press &apos;No&apos; for the Free Version ähnelt.
        /// </summary>
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tavern Bot ähnelt.
        /// </summary>
        public static string TavernBot {
            get {
                return ResourceManager.GetString("TavernBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tavern Visit DONE ähnelt.
        /// </summary>
        public static string TavernDone {
            get {
                return ResourceManager.GetString("TavernDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tavernstate ähnelt.
        /// </summary>
        public static string TavernState {
            get {
                return ResourceManager.GetString("TavernState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UNKNOWN ACTION: ähnelt.
        /// </summary>
        public static string UnknownAction {
            get {
                return ResourceManager.GetString("UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visitable ähnelt.
        /// </summary>
        public static string Visitable {
            get {
                return ResourceManager.GetString("Visitable", resourceCulture);
            }
        }
    }
}
